// Word pools. Lowercase a-z only, no proper nouns, no punctuation.
//
// Length bands are load-bearing: the tier decides damage and knockback scaling, so a
// word must never be moved between pools without re-checking the balance table.
// game/tests/engine.test.ts asserts every word sits inside its band.
//
// Provenance: the attack pools are drawn from a frequency-ranked English list
// (google-10000-english, most common first) so prompts are words a player actually knows
// and can spell. The hand-picked game-flavoured words this file started with are kept and
// merged in. Filtered for profanity, brand/web noise, abbreviations and lowercased proper
// nouns, because this game is aimed at the school market.
//
// GUARD_WORDS and RECOVERY_WORDS are written by hand rather than sampled: they need to
// read as "defend" and "get back up", and a randomly sampled 5-letter word does not.
// No word appears in both MID and the guard/recovery pools.
import type { WordTier } from "./types";

/** 3-4 characters. Fast, low damage, high base knockback. Creates space. */
export const LIGHT_WORDS = [
  "the", "you", "for", "all", "can", "had",
  "her", "was", "one", "our", "out", "day",
  "get", "has", "him", "his", "how", "man",
  "new", "now", "old", "see", "two", "way",
  "who", "boy", "did", "its", "let", "put",
  "say", "she", "too", "use", "run", "hit",
  "jam", "key", "lap", "map", "nap", "oak",
  "pad", "rag", "sap", "tap", "arc", "bay",
  "cod", "dip", "elm", "fig", "gap", "hue",
  "ivy", "jug", "keg", "lid", "mud", "nib",
  "orb", "pit", "rim", "sip", "tug", "urn",
  "van", "web", "yak", "zip", "bolt", "dash",
  "grip", "hash", "jolt", "knob", "lush", "mist",
  "nova", "pace", "quiz", "rush", "snap", "tide",
  "vibe", "warp", "yarn", "zone", "blur", "clap",
  "drum", "echo", "fist", "glow", "hook", "iron",
  "that", "from", "your", "have", "will", "home",
  "page", "free", "time", "site", "may", "what",
  "news", "any", "only", "when", "also", "help",
  "view", "been", "were", "some", "like", "than",
  "find", "date", "back", "top", "list", "name",
  "just", "over", "year", "into", "next", "used",
  "work", "last", "most", "buy", "data", "make",
  "them", "post", "city", "add", "such", "best",
  "then", "good", "well", "high", "each", "very",
  "book", "need", "many", "user", "said", "does",
  "set", "mail", "full", "life", "know", "days",
  "part", "real", "item", "must", "made", "off",
  "line", "send", "type", "car", "take", "area",
  "want", "long", "code", "show", "even", "much",
  "sign", "file", "open", "case", "same", "own",
  "care", "down", "end", "per", "big", "law",
  "size", "art", "shop", "text", "rate", "form",
  "love", "main", "call", "why", "save", "low",
  "card", "jobs", "food", "sale", "job", "teen",
  "room", "join", "men", "west", "look", "left",
  "team", "box", "week", "note", "live", "air",
  "plan", "yes", "hot", "cost", "test", "come",
  "cart", "play", "tax", "less", "got", "park",
  "side", "act", "red", "give", "sell", "body",
  "few", "east", "age", "club", "road", "gift",
  "hard", "pay", "four", "war", "blue", "easy",
  "fax", "yet", "star", "hand", "keep", "baby",
  "term", "film", "try", "god", "head", "cell",
  "self", "away", "once", "log", "sure", "cars",
  "tell", "able", "fun", "gold", "arts", "lot",
  "ask", "past", "due", "five", "upon", "says",
  "land", "done", "pro", "ever", "ago", "word",
  "talk", "via", "kids", "true", "else", "rock",
  "bad", "tips", "auto", "edit", "fast", "fact",
  "unit", "tech", "meet", "far", "feel", "bank",
  "risk", "town", "girl", "toys", "golf", "loan",
  "wide", "sort", "half", "step", "none", "lake",
  "fire", "chat", "loss", "face", "oil", "bit",
  "base", "near", "stay", "turn", "mean", "king",
  "copy", "drug", "cash", "seen", "port", "stop",
  "dog", "soon", "held", "mind", "lost", "tour",
  "menu", "hope", "wish", "role", "came", "hour",
  "gas", "six", "bush", "huge", "bid", "kind",
  "move", "logo", "nice", "sent", "band", "lead",
  "went", "mode", "fund", "male", "took", "inn",
  "song", "late", "fall", "idea", "win", "tool",
  "bed", "hill", "maps", "deal", "hold", "safe",
  "feed", "sea", "cut", "hall", "ship", "paid",
  "hair", "kit", "tree", "thus", "wall", "wine",
  "vote", "ways", "son", "rule", "told", "more",
  "link", "feet", "bin", "door", "cool", "uses",
  "pass", "fees", "skin", "ring", "pop", "boys",
  "deep", "rest", "pool", "mini", "fish", "eye",
  "pack", "born", "race", "debt", "core", "sets",
  "wood", "fee", "rent", "dark", "aid", "host",
  "fair", "gets", "fat", "saw", "dead", "trip",
  "poor", "eyes", "farm", "lord", "sub", "hear",
  "goes", "fan", "wife", "ten", "hits", "cat",
  "die", "jack", "flat", "flow", "path", "laws",
] as const;

/** 5-7 characters. Balanced. */
export const MID_WORDS = [
  "about", "after", "again", "below", "circuit", "click",
  "could", "count", "crash", "drive", "every", "field",
  "fight", "first", "focus", "found", "frame", "fresh",
  "front", "given", "glass", "grand", "grant", "grass",
  "great", "green", "group", "guess", "heart", "heavy",
  "horse", "house", "human", "ideal", "image", "index",
  "inner", "input", "issue", "joint", "known", "large",
  "laser", "learn", "light", "limit", "local", "logic",
  "loose", "lucky", "major", "match", "mayor", "metal",
  "might", "minor", "model", "mouse", "music", "never",
  "night", "noble", "noise", "north", "novel", "offer",
  "order", "other", "outer", "paint", "panel", "paper",
  "party", "peace", "phase", "phone", "photo", "pilot",
  "pitch", "place", "plain", "plant", "point", "pound",
  "power", "price", "pride", "print", "prize", "pulse",
  "quick", "quiet", "radio", "range", "rapid", "relay",
  "rider", "right", "river", "round", "route", "royal",
  "scene", "scope", "score", "sense", "serve", "seven",
  "shape", "share", "shine", "shock", "short", "sight",
  "skill", "slate", "smart", "smile", "solve", "sound",
  "south", "space", "spark", "speak", "speed", "spend",
  "spine", "spite", "split", "sport", "stage", "start",
  "state", "steam", "stick", "stock", "store", "story",
  "strip", "style", "table", "taste", "teach", "tense",
  "there", "thick", "thing", "think", "three", "timer",
  "title", "today", "token", "topic", "total", "touch",
  "trade", "treat", "trend", "trial", "tribe", "trick",
  "trust", "truth", "twist", "uncle", "under", "union",
  "unity", "until", "upper", "urban", "usual", "value",
  "video", "virus", "visit", "vital", "voice", "voltage",
  "water", "where", "which", "while", "white", "whole",
  "whose", "width", "woman", "world", "worry", "worth",
  "write", "wrong", "young", "search", "contact", "service",
  "people", "health", "should", "product", "system", "policy",
  "number", "please", "support", "message", "rights", "public",
  "school", "through", "review", "privacy", "company", "general",
  "reviews", "program", "united", "center", "travel", "report",
  "member", "details", "before", "hotels", "because", "results",
  "office", "design", "address", "within", "states", "subject",
  "between", "family", "special", "prices", "project", "version",
  "section", "sports", "related", "county", "members", "network",
  "systems", "without", "access", "current", "control", "history",
  "change", "rating", "during", "return", "account", "digital",
  "profile", "events", "another", "quality", "listing", "content",
  "country", "private", "little", "compare", "movies", "include",
  "college", "article", "provide", "source", "author", "around",
  "course", "process", "credit", "science", "estate", "select",
  "photos", "thread", "gallery", "however", "market", "library",
  "really", "action", "series", "second", "forums", "better",
  "medical", "friend", "looking", "issues", "street", "things",
  "working", "against", "person", "mobile", "payment", "student",
  "offers", "recent", "stores", "problem", "memory", "social",
  "august", "options", "create", "single", "example", "latest",
  "changes", "status", "browse", "seller", "always", "result",
  "groups", "release", "request", "making", "picture", "future",
  "meeting", "become", "similar", "garden", "schools", "million",
  "listed", "energy", "popular", "stories", "journal", "reports",
  "welcome", "central", "images", "notice", "council", "archive",
  "others", "format", "society", "months", "safety", "friends",
  "edition", "further", "updated", "having", "already", "studies",
  "common", "several", "living", "called", "display", "limited",
  "powered", "natural", "whether", "period", "weather", "average",
  "window", "region", "island", "record", "direct", "records",
  "update", "parts", "early", "miles", "present", "either",
  "works", "written", "federal", "rules", "final", "adult",
  "tickets", "centre", "cheap", "finance", "minutes", "third",
  "gifts", "reading", "topics", "usually", "videos", "percent",
  "getting", "global", "player", "lyrics", "often", "submit",
  "amount", "though", "thanks", "deals", "various", "weight",
  "choose", "points", "error", "camera", "clear", "receive",
  "domain", "methods", "chapter", "makes", "beauty", "manager",
  "taken", "models", "cases", "simple", "license", "annual",
  "later", "basic", "shows", "church", "method", "active",
  "figure", "holiday", "enough", "along", "among", "death",
  "writing", "brand", "higher", "effects", "created", "yellow",
  "kingdom", "thought", "stuff", "storage", "doing", "loans",
  "shoes", "entry", "nature", "orders", "summary", "growth",
  "notes", "agency", "western", "income", "force", "overall",
  "package", "players", "engine", "album", "started", "views",
  "plans", "double", "build", "screen", "types", "lines",
  "across", "needed", "season", "apply", "someone", "printer",
  "believe", "effect", "asked", "volume", "cross", "anyone",
  "silver", "inside", "mature", "rather", "weeks", "supply",
  "nothing", "certain", "running", "lower", "jewelry", "names",
  "skills", "islands", "advice", "career", "rental", "leave",
  "teens", "sellers", "middle", "cable", "taking", "values",
  "coming", "object", "lesbian", "machine", "length", "client",
  "returns", "capital", "follow", "sample", "shown", "culture",
  "flash", "george", "choice", "courses", "airport", "foreign",
  "artist", "outside", "levels", "channel", "letter", "phones",
  "ideas", "summer", "allow", "degree", "button", "homes",
  "super", "matter", "custom", "almost", "located", "asian",
  "editor", "cause", "rooms", "female", "primary", "cancer",
  "numbers", "reason", "browser", "spring", "answer", "purpose",
  "feature", "comes", "police", "cameras", "brown", "ratings",
  "forms", "happy", "smith", "wanted", "thank", "unique",
  "survey", "prior", "animal", "sources", "regular", "secure",
  "simply", "station", "paypal", "option", "master", "valley",
  "rentals", "built", "blood", "improve", "larger", "earth",
  "parents", "nokia", "impact", "kitchen", "strong", "wedding",
  "ground", "owners", "disease", "perfect", "classic", "basis",
  "command", "william", "express", "award", "ensure", "extra",
  "budget", "rated", "guides", "success", "maximum", "quite",
  "warning", "forward", "flowers", "stars", "lists", "owner",
  "retail", "animals", "useful", "housing", "takes", "bring",
  "catalog", "trying", "mother", "traffic", "joined", "agent",
  "valid", "modern", "senior", "testing", "charge", "units",
  "instead", "normal", "wrote", "ships", "entire", "leading",
  "fitness", "opinion", "output", "funds", "greater", "likely",
  "develop", "artists", "guest", "seems", "session", "multi",
  "century", "grade", "dating", "pacific", "filter", "mailing",
  "vehicle", "longer", "behind", "floor", "buying", "default",
  "require", "outdoor", "morning", "allows", "protein", "partner",
  "authors", "boards", "faculty", "parties", "mission", "string",
  "goods", "unless", "target", "except", "ability", "maybe",
  "moving", "brands", "places", "pretty", "winter", "battery",
  "youth", "incest", "medium", "break", "dance", "itself",
  "defined", "papers", "playing", "awards", "studio", "reader",
  "virtual", "device", "answers", "remote", "apple", "offered",
  "theory", "enjoy", "remove", "surface", "minimum", "visual",
  "variety", "martin", "manual", "agents", "repair", "civil",
  "songs", "fixed", "hands", "finally", "updates", "desktop",
  "classes", "sector", "jersey", "fully", "father", "quotes",
  "officer", "driver", "respect", "unknown", "workers", "campus",
  "showing", "their", "online", "these", "books", "links",
  "years", "items", "games", "hotel", "terms", "those",
  "using", "posted", "forum", "based", "black", "check",
  "being", "women", "pages", "posts", "media", "since",
  "board", "small", "times", "sites", "hours", "shall",
  "class", "money", "tools", "reply", "sales", "movie",
  "going", "study", "staff", "users", "comment", "legal",
  "above", "quote", "rates", "girls", "court", "audio",
  "files", "event", "needs", "areas", "cards", "child",
  "enter", "added",
] as const;

/** 8+ characters. Slow, high damage, high knockback scaling. */
export const HEAVY_WORDS = [
  "absolute", "abstract", "accurate", "activity", "addition", "advanced",
  "aircraft", "alliance", "although", "analysis", "announce", "anything",
  "apparent", "approach", "argument", "assembly", "attitude", "audience",
  "balanced", "baseball", "bathroom", "birthday", "boundary", "building",
  "business", "calendar", "campaign", "capacity", "category", "ceremony",
  "champion", "character", "chemical", "children", "civilian", "classify",
  "climbing", "clothing", "collapse", "colonial", "commence", "commerce",
  "complete", "compound", "computer", "conclude", "concrete", "conflict",
  "confused", "congress", "consider", "constant", "consumer", "contract",
  "contrast", "convince", "corridor", "coverage", "creative", "criminal",
  "critical", "cultural", "currency", "customer", "database", "daughter",
  "decision", "decrease", "definite", "delicate", "delivery", "describe",
  "designer", "detailed", "diabetes", "dialogue", "diameter", "director",
  "disaster", "discover", "dispatch", "distance", "distinct", "district",
  "division", "dominant", "dramatic", "duration", "dynamics", "economic",
  "educator", "election", "electric", "elemental", "elephant", "emergency",
  "emission", "employee", "engineer", "enormous", "entrance", "envelope",
  "equality", "estimate", "evaluate", "eventual", "evidence", "exchange",
  "exercise", "explicit", "exposure", "extended", "external", "facility",
  "familiar", "favorite", "feathers", "festival", "fighting", "finished",
  "firewall", "flexible", "floating", "football", "forecast", "foremost",
  "fraction", "fragment", "frequent", "friendly", "frontier", "function",
  "generous", "gentleman", "graduate", "graphics", "grateful", "guardian",
  "guidance", "hardware", "headline", "heritage", "historic", "hospital",
  "hundreds", "identify", "identity", "immediate", "incident", "increase",
  "indicate", "industry", "informal", "initiate", "innocent", "inspired",
  "instance", "integral", "interact", "interior", "internal", "interval",
  "involved", "judgment", "keyboard", "landscape", "language", "laughter",
  "learning", "leverage", "likewise", "location", "magnetic", "maintain",
  "majority", "mandated", "manuscript", "material", "mechanics", "medicine",
  "memorial", "mentally", "midnight", "military", "minerals", "minority",
  "momentum", "monument", "mortgage", "mountain", "movement", "multiple",
  "national", "negative", "neighbor", "notebook", "numbered", "observer",
  "occasion", "offering", "official", "operator", "opponent", "organize",
  "original", "outdoors", "overcome", "overhead", "parallel", "parental",
  "particle", "passenger", "password", "patience", "peaceful", "periodic",
  "personal", "persuade", "physical", "platform", "pleasure", "politics",
  "portrait", "position", "positive", "possible", "powerful", "practice",
  "precious", "precisely", "predicts", "premiere", "presence", "pressure",
  "previous", "priority", "prisoner", "probably", "producer", "professor",
  "profound", "progress", "prohibit", "property", "proposal", "prospect",
  "protocol", "province", "publicly", "punished", "purchase", "quantity",
  "question", "reaction", "receiver", "recently", "recovery", "regional",
  "register", "relative", "relevant", "reliable", "remember", "reminder",
  "removing", "repeated", "reporter", "research", "resemble", "resident",
  "resource", "response", "restrict", "retailer", "revealed", "revenues",
  "reversed", "reviewer", "rigorous", "romantic", "sandwich", "scenario",
  "schedule", "scientist", "scramble", "seasonal", "sections", "security",
  "sensible", "sentence", "separate", "sequence", "sergeant", "sessions",
  "shortage", "shoulder", "simplify", "situated", "sketches", "slightly",
  "software", "solution", "somebody", "southern", "speaking", "specific",
  "spelling", "spirited", "splendid", "sponsors", "squadron", "standard",
  "standing", "statement", "steering", "straight", "strategy", "strength",
  "stressed", "strictly", "stronger", "struggle", "students", "stunning",
  "suburban", "suddenly", "superior", "supposed", "surprise", "survival",
  "sweeping", "symbolic", "sympathy", "talented", "taxpayer", "teaching",
  "teammate", "tendency", "terminal", "terrible", "thousand", "together",
  "tomorrow", "tracking", "training", "transfer", "traveler", "treasure",
  "triangle", "tropical", "troubled", "ultimate", "universe", "unlikely",
  "unstable", "upcoming", "vacation", "valuable", "variable", "vertical",
  "violence", "warriors", "weakness", "weaponry", "whatever", "whenever",
  "wherever", "wildlife", "wireless", "withdraw", "workshop", "yourself",
  "information", "services", "products", "available", "copyright", "university",
  "management", "international", "development", "education", "internet", "community",
  "shipping", "reserved", "technology", "following", "resources", "pictures",
  "including", "directory", "government", "shopping", "department", "description",
  "insurance", "different", "categories", "conditions", "features", "provided",
  "required", "accessories", "questions", "application", "articles", "feedback",
  "financial", "equipment", "programs", "performance", "experience", "important",
  "activities", "additional", "something", "professional", "committee", "problems",
  "interest", "reference", "companies", "computers", "president", "includes",
  "discussion", "entertainment", "agreement", "messages", "marketing", "association",
  "provides", "collection", "solutions", "electronics", "planning", "technical",
  "microsoft", "conference", "environment", "downloads", "applications", "document",
  "requirements", "individual", "projects", "subscribe", "included", "everything",
  "production", "commercial", "advertising", "received", "treatment", "newsletter",
  "archives", "knowledge", "magazine", "currently", "construction", "registered",
  "protection", "policies", "listings", "engineering", "published", "corporate",
  "customers", "materials", "designed", "countries", "discount", "standards",
  "political", "advertise", "environmental", "availability", "european", "employment",
  "commission", "contents", "supplies", "administration", "institute", "sponsored",
  "electronic", "continue", "benefits", "condition", "effective", "organization",
  "selection", "corporation", "executive", "necessary", "according", "particular",
  "facilities", "opportunities", "appropriate", "actually", "statistics", "investment",
  "christmas", "starting", "registration", "furniture", "structure", "releases",
  "distribution", "industrial", "potential", "featured", "responsible", "communications",
  "associated", "foundation", "documents", "communication", "everyone", "independent",
  "operating", "developed", "telephone", "population", "navigation", "operations",
  "therefore", "christian", "understand", "publications", "worldwide", "connection",
  "publisher", "networks", "introduction", "carolina", "properties", "overview",
  "accommodation", "excellent", "opportunity", "assessment", "especially", "interface",
  "partners", "operation", "existing", "selected", "patients", "restaurants",
  "beautiful", "locations", "significant", "technologies", "directly", "manufacturer",
  "providing", "searches", "authority", "considered", "programme", "canadian",
  "enterprise", "educational", "employees", "alternative", "processing", "responsibility",
  "resolution", "publication", "relations", "contains", "photography", "republic",
  "components", "academic", "assistance", "completed", "expected", "organizations",
  "northern", "proposed", "otherwise", "reported", "transportation", "disclaimer",
  "membership", "modified", "released", "recommended", "approved", "background",
  "maintenance", "functions", "trademarks", "phentermine", "submitted", "keywords",
  "television", "interested", "purposes", "throughout", "established", "programming",
  "regarding", "instructions", "teachers", "subjects", "increased", "understanding",
  "beginning", "associates", "requires", "instruments", "businesses", "specified",
  "restaurant", "procedures", "relationship", "traditional", "sometimes", "families",
  "themselves", "transport", "interesting", "evaluation", "accepted", "implementation",
  "galleries", "references", "presented", "agencies", "literature", "respective",
  "michigan", "columbia", "definition", "secretary", "networking", "australian",
  "magazines", "packages", "individuals", "colorado", "guidelines", "installation",
  "described", "attention", "difference", "illinois", "regulations", "elements",
  "certificate", "minister", "directions", "visitors", "documentation", "automotive",
  "successful", "communities", "clinical", "situation", "sciences", "publishing",
  "developing", "determine", "temperature", "announcements", "historical", "ringtones",
  "difficult", "scientific", "satellite", "accounts", "particularly", "settings",
  "functional", "holidays", "monitoring", "architecture", "thinking", "recommend",
  "hardcore", "provider", "optional", "dictionary", "accounting", "manufacturing",
  "generally", "continued", "techniques", "websites", "religion", "permission",
  "measures", "generation", "component", "guarantee", "processes", "meetings",
  "interests", "username", "produced", "paperback", "classifieds", "supported",
  "competition", "creating", "providers", "characters", "attorney", "thousands",
  "apartments", "auctions", "generated", "administrative", "informed", "thoughts",
  "practices", "reporting", "essential", "affiliate", "immediately", "machines",
  "designated", "integrated", "configuration", "merchant", "comprehensive", "universal",
  "presentation", "languages", "compliance", "vehicles", "improvement", "pennsylvania",
  "examples", "challenge", "motorola", "acceptance", "strategies", "intended",
  "affiliates", "multimedia", "certified", "computing", "interactive", "requests",
  "procedure", "leadership", "religious", "breakfast", "developer", "approximately",
  "domestic", "recommendations", "comparison", "automatically", "minnesota", "williams",
  "printing", "approval", "contacts", "adventure", "matching", "institutions",
  "assistant", "advertisement", "headlines", "yesterday", "compared", "determined",
  "wholesale", "extension", "statements", "completely", "lighting", "portable",
  "electrical", "applicable", "returned", "manufacturers", "classical", "warranty",
  "dedicated", "direction", "basketball", "comments", "wisconsin", "obtained",
  "personnel", "supplied", "identified", "opinions", "professionals", "advantage",
  "newsletters", "payments",
] as const;

/** Exactly GUARD_WORD_LENGTH (5) characters. Short enough to be a real parry window. */
export const GUARD_WORDS = [
  "block", "brace", "cover", "dodge", "fence", "guard",
  "hedge", "parry", "poise", "rally", "raise", "ready",
  "repel", "rigid", "shell", "spike", "stall", "stand",
  "steel", "stern", "stiff", "still", "stout", "strap",
  "stone", "stoop", "tower", "wield", "avert", "blunt",
  "clamp", "dense", "erect", "evade", "forge", "level",
  "lever", "nerve", "plate", "press", "prime", "proof",
  "sharp", "solid", "stake", "stark", "stead", "sting",
  "tight", "tough", "tried", "vigil", "watch",
] as const;

/** Exactly RECOVERY_WORD_LENGTH (5) characters. Typed while falling, must be easy. */
export const RECOVERY_WORDS = [
  "catch", "climb", "cling", "float", "glide", "grasp",
  "hoist", "hover", "latch", "ledge", "mount", "perch",
  "reach", "scale", "swing", "vault", "surge", "boost",
  "drift", "fling", "heave", "hitch", "lunge", "pivot",
  "scoop", "seize", "shift", "slide", "swoop", "throw",
  "trail", "tread", "wedge", "wheel", "whirl", "wring",
  "carry", "chute", "crawl", "crest", "flick", "guide",
  "hinge", "march", "plane", "probe", "shove", "skate",
  "spare", "steer", "storm", "strut", "sweep", "swift",
  "tempo", "track", "train", "truss", "turbo",
] as const;

export const POOLS: Record<WordTier, readonly string[]> = {
  light: LIGHT_WORDS,
  mid: MID_WORDS,
  heavy: HEAVY_WORDS,
};

export const TIER_ORDER: readonly WordTier[] = ["light", "mid", "heavy"];
